### ISSUE TITLE
新版本的 eslint 废弃了 ecmaFeatures 选项

### ISSUE THREAD

**Issue by elliothux** [imweb/eslint-config-imweb#5]
lint 时提示: The 'ecmaFeatures' config file property is deprecated, and has no effect.

**Comment by Red626** [comment]
旧版本的eslint-config-airbnb中存在将ecmafeatures作文顶层属性的情况，升级eslint-config-imweb的dependencies可以解决

**Comment by avwo** [comment]
更新到最新版本
