### ISSUE TITLE
建议：禁用几条规则

### ISSUE THREAD

**Issue by jinwei233** [imweb/eslint-config-imweb#9]
### jsx-a11y/anchor-is-valid

![image](https://user-images.githubusercontent.com/243645/42440148-679e3c86-8397-11e8-9770-c0afdb5df085.png)

### global-require
![image](https://user-images.githubusercontent.com/243645/42485930-574c0c1a-842c-11e8-88c9-ca71c1daaac0.png)

### 允许使用 new
![image](https://user-images.githubusercontent.com/243645/42554494-b031416a-8517-11e8-8596-abafa0d5a39c.png)

### 支持简单的短路运算符

`abc && abc()` 太常见了，建议开启支持。比如 [eslint-config-fbjs](https://github.com/facebook/fbjs/blob/master/packages/eslint-config-fbjs/index.js#L220) 就开启了支持

![image](https://user-images.githubusercontent.com/243645/42559525-ea7cd726-8526-11e8-9960-76b839409e58.png)

参见
- [1] https://github.com/airbnb/javascript/issues/963
- [2] http://eslint.cn/docs/2.0.0/rules/no-unused-expressions

**Comment by elvinn** [comment]
已经在 [Pull - 11](https://github.com/imweb/eslint-config-imweb/pull/11) 完成
